version: '3'

services:
  importer:
    image: ghcr.io/iverly/f1-signalr-to-kafka-importer:latest
    build:
      context: .
      dockerfile: Dockerfile.importer
    restart: unless-stopped
    volumes:
      - ./f1-events.txt:/tmp/f1-events.txt

  exporter:
    image: ghcr.io/iverly/f1-signalr-to-kafka-exporter:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - EXPORTER_FILE_PATH=/tmp/f1-events.txt
      - EXPORTER_KAFKA_BROKER=kafka:19092
    volumes:
      - ./f1-events.txt:/tmp/f1-events.txt

  kafka:
    image: "bitnami/kafka:3.4.0"
    restart: unless-stopped
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=DOCKER_INTERNAL
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,PLAINTEXT://:9092,DOCKER_INTERNAL://:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER_INTERNAL:PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,DOCKER_INTERNAL://kafka:19092
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=wunIH31zRY2LvJKHyrKoVQ
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"

  conduktor-platform:
    image: conduktor/conduktor-platform:latest
    restart: unless-stopped
    environment:
      CDK_ORGANIZATION_NAME: "demo"
      CDK_ADMIN_EMAIL: "admin@admin.io"
      CDK_ADMIN_PASSWORD: "admin"
      CDK_CLUSTERS_0_ID: "default"
      CDK_CLUSTERS_0_NAME: "My Kafka Cluster"
      CDK_CLUSTERS_0_COLOR: "#0013E7"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "DOCKER_INTERNAL://kafka:19092"
    ports:
      - "8080:8080"
    volumes:
      - conduktor_data:/var/conduktor
    depends_on:
      - kafka

volumes:
  conduktor_data:
  kafka_data:

